# Site settings
title: "MRP Resume"
description: "Mohammad Reza Pazooki Resume On GitHub Page."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mohammad Reza Pazooki"
resume_title:                   "MRP - Web Developer"
resume_contact_email:           "ipazooki@gmail.com"
resume_contact_telephone:       "+98-9352463668"
resume_contact_address:         "Tehran, Iran"
resume_header_contact_info: "https://www.linkedin.com/in/pazooki | ipazooki@gmail.com"
resume_header_intro: "<p>I am a Senior Web Developer / Designer with more than 5 years of experience, I have spent most of my career working in C#, Web API, NServiceBus, AngularJs and Service Oriented Environment. I would like to pursue my career in a work environment that will utilize and reinforce my technical skills and abilities and also to apply and gain new cutting edge skills and experience in a rapidly changing field. I have Experience of working in the complete software development life cycle as a Scrum Master using Agile methodology, involving development, testing and maintenance.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/iPazooki"
  resume_twitter_url:           "https://twitter.com/ipazooki"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/pazooki"
  resume_linkedin_url:          "https://www.linkedin.com/in/pazookir"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
